FROM node:22.13-alpine AS development

WORKDIR /app

COPY package*.json ./

COPY prisma ./prisma

RUN npm install

COPY . .

RUN npx prisma generate --schema=./prisma/schema.prisma

EXPOSE 8443

CMD ["npm", "run", "dev"]
